export PATH=export PATH=/home/zrz0517/OPTEE/toolchains/aarch64/bin:$PATH
CC=/home/zrz0517/study/chain_attestation/OP-DFI/toolchain/llvm-project/build/bin/clang CXX=/home/zrz0517/study/chain_attestation/OP-DFI/toolchain/llvm-project/build/bin/clang++   CXXFLAGS="-O0 -Xclang -disable-O0-optnone --target=aarch64-linux-gnu  -g0" LDFLAGS="-fuse-ld=/home/zrz0517/study/chain_attestation/OP-DFI/toolchain/llvm-project/build/bin/ld.lld"   ./waf configure --board=sitl --toolchain=aarch64-linux-gnu --disable-scripting

 ./waf copter 
cd build/sitl 
/home/zrz0517/study/chain_attestation/OP-DFI/toolchain/llvm-project/build/bin/llvm-ar -s lib/libArduCopter_libs.a

/home/zrz0517/study/chain_attestation/OP-DFI/toolchain/llvm-project/build/bin/clang++  --target=aarch64-linux-gnu -Wl,--export-dynamic -fno-exceptions -Wl,--gc-sections -fuse-ld=lld -flto -Wl,--plugin-opt=emit-llvm -Wl,--lto-whole-program-visibility -O0 -Xclang -disable-O0-optnone  ArduCopter/AP_Arming.cpp.47.o ArduCopter/AP_Rally.cpp.47.o ArduCopter/AP_State.cpp.47.o ArduCopter/Attitude.cpp.47.o ArduCopter/Copter.cpp.47.o ArduCopter/GCS_Copter.cpp.47.o ArduCopter/GCS_Mavlink.cpp.47.o ArduCopter/Log.cpp.47.o ArduCopter/Parameters.cpp.47.o ArduCopter/RC_Channel.cpp.47.o ArduCopter/UserCode.cpp.47.o ArduCopter/UserParameters.cpp.47.o ArduCopter/afs_copter.cpp.47.o ArduCopter/autoyaw.cpp.47.o ArduCopter/avoidance.cpp.47.o ArduCopter/avoidance_adsb.cpp.47.o ArduCopter/baro_ground_effect.cpp.47.o ArduCopter/commands.cpp.47.o ArduCopter/compassmot.cpp.47.o ArduCopter/crash_check.cpp.47.o ArduCopter/ekf_check.cpp.47.o ArduCopter/esc_calibration.cpp.47.o ArduCopter/events.cpp.47.o ArduCopter/failsafe.cpp.47.o ArduCopter/fence.cpp.47.o ArduCopter/heli.cpp.47.o ArduCopter/inertia.cpp.47.o ArduCopter/land_detector.cpp.47.o ArduCopter/landing_gear.cpp.47.o ArduCopter/mode.cpp.47.o ArduCopter/mode_acro.cpp.47.o ArduCopter/mode_acro_heli.cpp.47.o ArduCopter/mode_althold.cpp.47.o ArduCopter/mode_auto.cpp.47.o ArduCopter/mode_autorotate.cpp.47.o ArduCopter/mode_autotune.cpp.47.o ArduCopter/mode_avoid_adsb.cpp.47.o ArduCopter/mode_brake.cpp.47.o ArduCopter/mode_circle.cpp.47.o ArduCopter/mode_drift.cpp.47.o ArduCopter/mode_flip.cpp.47.o ArduCopter/mode_flowhold.cpp.47.o ArduCopter/mode_follow.cpp.47.o ArduCopter/mode_guided.cpp.47.o ArduCopter/mode_guided_nogps.cpp.47.o ArduCopter/mode_land.cpp.47.o ArduCopter/mode_loiter.cpp.47.o ArduCopter/mode_poshold.cpp.47.o ArduCopter/mode_rtl.cpp.47.o ArduCopter/mode_smart_rtl.cpp.47.o ArduCopter/mode_sport.cpp.47.o ArduCopter/mode_stabilize.cpp.47.o ArduCopter/mode_stabilize_heli.cpp.47.o ArduCopter/mode_systemid.cpp.47.o ArduCopter/mode_throw.cpp.47.o ArduCopter/mode_turtle.cpp.47.o ArduCopter/mode_zigzag.cpp.47.o ArduCopter/motor_test.cpp.47.o ArduCopter/motors.cpp.47.o ArduCopter/navigation.cpp.47.o ArduCopter/precision_landing.cpp.47.o ArduCopter/radio.cpp.47.o ArduCopter/sensors.cpp.47.o ArduCopter/standby.cpp.47.o ArduCopter/surface_tracking.cpp.47.o ArduCopter/system.cpp.47.o ArduCopter/takeoff.cpp.47.o ArduCopter/takeoff_check.cpp.47.o ArduCopter/terrain.cpp.47.o ArduCopter/toy_mode.cpp.47.o ArduCopter/tuning.cpp.47.o -Llib -lArduCopter_libs -o arducopter.bc

/home/zrz0517/study/chain_attestation/OP-DFI/toolchain/llvm-project/build/bin/clang++ -DHAL_HAVE_AP_ROMFS_EMBEDDED_H  -fno-slp-vectorize --target=aarch64-linux-gnu  --gcc-toolchain=/home/zrz0517/OPTEE/toolchains/aarch64 --sysroot=/home/zrz0517/OPTEE/toolchains/aarch64/bin/../aarch64-linux-gnu/libc  -I/home/zrz0517/study/chain_attestation/OP-DFI/toolchain/klee/include -O0 -Xclang -disable-O0-optnone -c -emit-llvm -include ap_config.h -include ap_config.h -Ilibraries -Ilibraries/GCS_MAVLink -Imodules/uavcan/libuavcan/include/dsdlc_generated -I. -I../../libraries -I../../libraries/AP_Common/missing -I../../modules/uavcan/libuavcan/include -I/home/zrz0517/study/chain_attestation/OP-DFI/ardupilot/libraries/AC_AttitudeControl  -DSKETCHBOOK=\"/home/zrz0517/study/chain_attestation/OP-DFI/ardupilot\" -DAP_CUSTOMCONTROL_ENABLED=1 -DAP_SCRIPTING_CHECKS=1 -DAP_SCRIPTING_ENABLED=1 -DCONFIG_HAL_BOARD=HAL_BOARD_SITL -DCONFIG_HAL_BOARD_SUBTYPE=HAL_BOARD_SUBTYPE_NONE -DENABLE_HEAP=1  -DENABLE_ONVIF=0 -DHAL_PROBE_EXTERNAL_I2C_BAROS=1 -DLUA_32BITS=1 -DUAVCAN_CPP_VERSION=UAVCAN_CPP03 -DUAVCAN_NO_ASSERTIONS=1 -DUAVCAN_NULLPTR=nullptr  -DAPM_BUILD_DIRECTORY=APM_BUILD_ArduCopter -DSKETCH=\"ArduCopter\"   /home/zrz0517/study/chain_attestation/OP-DFI/copter_klee_entry/symbolic_entry.c -o /home/zrz0517/study/chain_attestation/OP-DFI/copter_klee_entry/symbolic_entry.bc

/home/zrz0517/study/chain_attestation/OP-DFI/toolchain/llvm-project/build/bin/clang++ -DHAL_HAVE_AP_ROMFS_EMBEDDED_H  -fno-slp-vectorize --target=aarch64-linux-gnu  --gcc-toolchain=/home/zrz0517/OPTEE/toolchains/aarch64 --sysroot=/home/zrz0517/OPTEE/toolchains/aarch64/bin/../aarch64-linux-gnu/libc  -I/home/zrz0517/study/chain_attestation/OP-DFI/toolchain/klee/include -O0 -Xclang -disable-O0-optnone -c -emit-llvm -include ap_config.h -include ap_config.h -Ilibraries -Ilibraries/GCS_MAVLink -Imodules/uavcan/libuavcan/include/dsdlc_generated -I. -I../../libraries -I../../libraries/AP_Common/missing -I../../modules/uavcan/libuavcan/include -I/home/zrz0517/study/chain_attestation/OP-DFI/ardupilot/libraries/AC_AttitudeControl -I../../ArduCopter/ -DSKETCHBOOK=\"/home/zrz0517/study/chain_attestation/OP-DFI/ardupilot\" -DAP_CUSTOMCONTROL_ENABLED=1 -DAP_SCRIPTING_CHECKS=1 -DAP_SCRIPTING_ENABLED=1 -DCONFIG_HAL_BOARD=HAL_BOARD_SITL -DCONFIG_HAL_BOARD_SUBTYPE=HAL_BOARD_SUBTYPE_NONE -DENABLE_HEAP=1  -DENABLE_ONVIF=0 -DHAL_PROBE_EXTERNAL_I2C_BAROS=1 -DLUA_32BITS=1 -DUAVCAN_CPP_VERSION=UAVCAN_CPP03 -DUAVCAN_NO_ASSERTIONS=1 -DUAVCAN_NULLPTR=nullptr  -DAPM_BUILD_DIRECTORY=APM_BUILD_ArduCopter -DSKETCH=\"ArduCopter\"   /home/zrz0517/study/chain_attestation/OP-DFI/copter_klee_entry/symbolic_entry.c -o /home/zrz0517/study/chain_attestation/OP-DFI/copter_klee_entry/symbolic_entry.bc
/home/zrz0517/study/chain_attestation/OP-DFI/toolchain/llvm-project/build/bin/llvm-link arducopter.bc /home/zrz0517/study/chain_attestation/OP-DFI/copter_klee_entry/symbolic_entry.bc  -o symbolic_execute.bc

/home/zrz0517/study/chain_attestation/OP-DFI/toolchain/llvm-project/build/bin/llvm-dis symbolic_execute.bc -o symbolic_execute.ll


export LD_LIBRARY_PATH=~/study/chain_attestation/OP-DFI/toolchain/stp/deps/cadical/build:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=~/study/chain_attestation/OP-DFI/toolchain/stp/deps/cadiback:$LD_LIBRARY_PATH
/home/zrz0517/study/chain_attestation/OP-DFI/toolchain/klee/build/bin/klee  symbolic_execute.bc --entry-point=_Z24symbolic_execution_beginv --debug-dump-stp-queries  --log-partial-queries-early --write-paths  --write-kqueries --write-smt2s  --write-sym-paths    --write-test-info 
/home/zrz0517/study/chain_attestation/OP-DFI/toolchain/llvm-project/build/bin/llvm-nm symbolic_execute.bc | grep pos_control
/home/zrz0517/study/chain_attestation/OP-DFI/toolchain/llvm-project/build/bin/llvm-nm  arducopter.bc | grep pos_control
python3 /home/zrz0517/study/chain_attestation/OP-DFI/slack_estimation/prepare_formula.py  ./klee-last /tmp/processed_formula 30 16 6 
/home/zrz0517/study/chain_attestation/OP-DFI/toolchain/llvm-project/build/bin/opt -f -enable-new-pm=0 -load /home/zrz0517/study/chain_attestation/OP-DFI/toolchain/llvm-project/build/lib/LLVMCode_version_generation.so -code_duplicate -myarg=1 arducopter.bc -o arducopter.bc.v1 
/home/zrz0517/study/chain_attestation/OP-DFI/toolchain/llvm-project/build/bin/opt -f -enable-new-pm=0 -load /home/zrz0517/study/chain_attestation/OP-DFI/toolchain/SVF/Release-build/tools/OPDFI/libdfAnalysis.so -df_analysis -version_id=1 -info_file=/tmp/processed_formula/code_version_id_coverage  arducopter.bc.v1 -o code_ver.bc.v1.dfi 