#!/bin/bash
CURRENT_DIR=$(pwd)
ROOT_DIR="${CURRENT_DIR}/.."
echo "设置 LLVM 相关路径"
LLVM_OPT="${ROOT_DIR}/llvm-16.0/llvm-project-16.0.0/build/bin/opt"
LLVM_DIS="${ROOT_DIR}/llvm-16.0/llvm-project-16.0.0/build/bin/llvm-dis"
LLVM_CHECKPOINT_PASS="${ROOT_DIR}/llvm-16.0/llvm-project-16.0.0/build/lib/LLVMInsertCheckPointsOnLoop.so"
LLVM_NOVA_PASS="${ROOT_DIR}/llvm-16.0/llvm-project-16.0.0/build/lib/LLVMNova.so"

echo "进入构建目录"
cd bd/src/"$1" || { echo "目录不存在"; exit 1; }
echo " 插入 CheckPoint以及start_collecting"
$LLVM_OPT -load $LLVM_CHECKPOINT_PASS --insert-check-point-on-loop -enable-new-pm=0 -opaque-pointers=0 < ./"$1"_after_compartment_llvm_link.ll > ./"$1"_after_insert_checkpoint.bc

$LLVM_DIS -opaque-pointers=0 "$1"_after_insert_checkpoint.bc -o "$1"_after_insert_checkpoint.ll

echo "进行 LowerSwitch 转换"
$LLVM_OPT -opaque-pointers=0 --lowerswitch -enable-new-pm=0 < "$1"_after_insert_checkpoint.ll > "$1"_after_lower_switch.bc

$LLVM_DIS -opaque-pointers=0 "$1"_after_lower_switch.bc -o "$1"_after_lower_switch.ll

echo "enable data-flow integity"
$LLVM_OPT -load  $LLVM_NOVA_PASS  -enable-new-pm=0  -opaque-pointers=0 -nova --nova-indirect-call-analysis-filepath=./indirectcall.txt --nova-analysis-direct-callfilepath=./direct_call_result.txt "$1"_after_lower_switch.bc > "$1"_enable_data_flow.bc  

$LLVM_DIS -opaque-pointers=0 "$1"_enable_data_flow.bc -o "$1"_enable_data_flow.ll

echo "插入 Dummy Code"
$LLVM_OPT -load  $LLVM_CHECKPOINT_PASS --insert-dummy-code -enable-new-pm=0 -opaque-pointers=0 < "$1"_enable_data_flow.bc > "$1"_after_insert_dummy.bc 
$LLVM_DIS -opaque-pointers=0 "$1"_after_insert_dummy.bc -o "$1"_after_insert_dummy.ll

echo "复制生成的 IR 文件到目标目录"
cp "$1"_after_insert_dummy.ll ../../../../pre-analysis16.0/util/output/after_insert_dummy.ll
cp ./only_called_once_func_backup.txt ../../../../pre-analysis16.0/util/output/
echo  "进入 AutoGenerateDummy 目录"
cd ../../../../pre-analysis16.0/util/generate_final_hash || { echo "AutoGenerateDummy 目录不存在"; exit 1; }

echo " 运行 Python 脚本生成 dummy.S"
python3 AutoGenerateDummy.py

echo "复制 dummy.S 到目标目录"
cp ../output/dummycode.S ../../../measurement-engine/first-measure-in-secure-world/runtime

echo "流程完成！"
cd ../../../embench_test || { echo "embench目录不存在"; exit 1; }